server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8


spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /tmp/**
  resources:
    static-locations: classpath:/tmp/

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weteam?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filter:
        wall:
          config:
            condition-op-xor-allow:

  jpa:
    database: MYSQL
#    show-sql: true
    hibernate:
      ddl-auto: update
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

  redis:
    host: 39.105.190.51     # 服务器地址
    port: 6378          # 开发所用端口
#    password: 123456
    timeout: 5000       # 链接超时时间 ms
    jedis:
        pool:             # 连接池
          max-active: 8   # 最大激活数
          max-idle: 8     # 最大空闲数
          max-wait: -1    # 最大等待时间
          min-idle: 0     # 最小空闲活动连接数
    database: 0           # 数据库索引


  # 文件上传
  servlet:
    multipart:
      max-file-size: 5MB      # 单文件
      max-request-size: 10MB  # 总文件


#mybatis:
#  type-aliases-package: com.weteam.model
#  mapper-locations: classpath*:mapper/*.xml

#自定义属性
# miniProgram
wechat:
  appId: wx42ac70376e53ee05
  appSecret: 13ff5f902585ed936bbc7c1f786644d3
  url: https://api.weixin.qq.com/sns/jscode2session

# 公众号
wx:
  mp:
    myOpenId: o0fNJxCNgwtbQ4sr3GcKEEZtFY_M
    configs:
      - appId: wx3925f5e9929075e1
        secret: a1ace361289cf41b1d798d6b0df2621d
        token: iamk                                           # 微信服务器验证需要的自定义token
        aesKey: j2DsWmU8Tkfw5VrvJHfELd6P3VU4hcPx9P5xcPSran6
        applyTemplateId: lJQFG72EBHH2LbPjgfVP1ETCfEoVRROGGgm5ZhOrqi8  # 申请加入模板id
        informTemplateId: NeUX6RGvkLylaBS3CqHD_Ztk81-h311WpGVMgfoTfAo  # 消息通知模板id

upload:
  avatarPath: /home/nginx/html/static/tmp/
  avatarPath2: /tmp/

# 七牛云
qiniu:
  accessKey: o7QJ7paYAekMsth9ULf1bBclnYVQf-MxNNSJ3qpB
  secretKey: O4COxC1ZEH3viiXi9Zl7fBfoJeqH-XFojFOAO_Ly
  bucketName: iamk-weteam
  fileDomain: http://cdn.img.iamk.top

baseUploadUrl: /tmp

# log4j2
logging:
  config: classpath:log4j2.xml
  level:
    cn.jay.repository: trace
#  level:
#    org:
#      springframework: INFO

